version: '2'
services:
    zookeeper:
        container_name: zookeeper
        image: zookeeper:3.4.8
        restart: always
        networks:
            kafka-net:
                ipv4_address: 172.19.0.101
        ports:
            - "30020:22"
            - "30000:2181"

    kafka1:
        container_name: kafka1
        image: kafka:2.11-0.10.1.0
        restart: always
        volumes:
            - /data/kafka:/kafka
        networks:
            kafka-net:
                ipv4_address: 172.19.0.201
        ports:
            - "30021:22"
            - "30001:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 10.129.7.144
            KAFKA_ADVERTISED_PORT: 30001
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    kafka2:
        container_name: kafka2
        image: kafka:2.11-0.10.1.0
        restart: always
        volumes:
            - /data/kafka:/kafka
        networks:
            kafka-net:
                ipv4_address: 172.19.0.202
        ports:
            - "30022:22"
            - "30002:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 10.129.7.144
            KAFKA_ADVERTISED_PORT: 30002
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    kafka3:
        container_name: kafka3
        image: kafka:2.11-0.10.1.0
        restart: always
        volumes:
            - /data/kafka:/kafka
        networks:
            kafka-net:
                ipv4_address: 172.19.0.203
        ports:
            - "30023:22"
            - "30003:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 10.129.7.144
            KAFKA_ADVERTISED_PORT: 30003
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

networks:
    kafka-net:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
        ipam:
            driver: default
            config:
            - subnet: 172.19.0.0/24
              gateway: 172.19.0.1
              ip_range: 172.19.0.254/24
