version: '2'
services:
    elasticsearch1:
        container_name: elasticsearch-A
        image: elasticsearch:5.2.2
        restart: always
        volumes:
            - /data/elasticsearch-A:/elasticsearch
        networks:
            cassandra-net:
                ipv4_address: 172.20.0.100
        ports:
            - "40022:22"
            - "49200:9200"
            - "49300:9300"
        environment:
            HOSTNAME: elasticsearch-A
            ELASTICSEARCH_CLUSTER_NAME: TestCluster
            ELASTICSEARCH_NODE_NAME: elasticsearch-A
            ELASTICSEARCH_PATH_DATA: /elasticsearch
            ELASTICSEARCH_PATH_LOGS: /logs
            ELASTICSEARCH_NETWORK_HOST: 172.20.0.100
            ELASTICSEARCH_HTTP_PORT: 9200
            ELASTICSEARCH_DISCOVERY_ZEN_PING_UNICAST_HOSTS: "[\"172.20.0.100\",\"172.20.0.101\",\"172.20.0.102\"]"

    elasticsearch2:
        container_name: elasticsearch-B
        image: elasticsearch:5.2.2
        restart: always
        volumes:
            - /data/elasticsearch-B:/elasticsearch
        networks:
            cassandra-net:
                ipv4_address: 172.20.0.101
        ports:
            - "40023:22"
            - "49201:9200"
            - "49301:9300"
        environment:
            HOSTNAME: elasticsearch-B
            ELASTICSEARCH_CLUSTER_NAME: TestCluster
            ELASTICSEARCH_NODE_NAME: elasticsearch-B
            ELASTICSEARCH_PATH_DATA: /elasticsearch
            ELASTICSEARCH_PATH_LOGS: /logs
            ELASTICSEARCH_NETWORK_HOST: 172.20.0.101
            ELASTICSEARCH_HTTP_PORT: 9200
            ELASTICSEARCH_DISCOVERY_ZEN_PING_UNICAST_HOSTS: "[\"172.20.0.100\", \"172.20.0.101\", \"172.20.0.102\"]"

    elasticsearch3:
        container_name: elasticsearch-C
        image: elasticsearch:5.2.2
        restart: always
        volumes:
            - /data/elasticsearch-C:/elasticsearch
        networks:
            cassandra-net:
                ipv4_address: 172.20.0.102
        ports:
            - "40024:22"
            - "49202:9200"
            - "49302:9300"
        environment:
            HOSTNAME: elasticsearch-C
            ELASTICSEARCH_CLUSTER_NAME: TestCluster
            ELASTICSEARCH_NODE_NAME: elasticsearch-C
            ELASTICSEARCH_PATH_DATA: /elasticsearch
            ELASTICSEARCH_PATH_LOGS: /logs
            ELASTICSEARCH_NETWORK_HOST: 172.20.0.102
            ELASTICSEARCH_HTTP_PORT: 9200
            ELASTICSEARCH_DISCOVERY_ZEN_PING_UNICAST_HOSTS: "[\"172.20.0.100\", \"172.20.0.101\", \"172.20.0.102\"]"

networks:
    cassandra-net:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
        ipam:
            driver: default
            config:
            - subnet: 172.20.0.0/24
              gateway: 172.20.0.1
              ip_range: 172.20.0.254/24

